"""Runtime loader for the trained crop recommendation model."""

import os
from functools import lru_cache


FEATURES = ["N", "P", "K", "temperature", "humidity", "ph", "rainfall"]
MODEL_PATH = os.getenv("CROP_MODEL_PATH", "ml_models/crop_recommendation_model.joblib")


def has_complete_trained_features(inputs):
    """Return whether all trained model features are present."""
    return all(inputs.get(field) is not None for field in FEATURES)


def _format_inputs(inputs):
    values = {
        "N": float(inputs["N"]),
        "P": float(inputs["P"]),
        "K": float(inputs["K"]),
        "temperature": float(inputs["temperature"]),
        "humidity": float(inputs["humidity"]),
        "ph": float(inputs["ph"]),
        "rainfall": float(inputs["rainfall"]),
    }
    try:
        import pandas as pd
        return pd.DataFrame([values], columns=FEATURES)
    except ImportError:
        return [[values[feature] for feature in FEATURES]]


@lru_cache(maxsize=1)
def load_crop_model():
    """Load the trained crop model artifact if available."""
    if not os.path.exists(MODEL_PATH):
        return None

    try:
        import joblib
    except ImportError:
        return None

    return joblib.load(MODEL_PATH)


def predict_with_trained_model(inputs, top_k=3):
    """Return ranked predictions from the trained model artifact."""
    artifact = load_crop_model()
    if artifact is None:
        return None

    model = artifact["model"]
    labels = artifact["labels"]
    features = _format_inputs(inputs)

    if hasattr(model, "predict_proba"):
        probabilities = model.predict_proba(features)[0]
        ranked_indexes = probabilities.argsort()[::-1][:top_k]
        predictions = []
        for rank, index in enumerate(ranked_indexes, start=1):
            crop = labels[index]
            confidence = round(float(probabilities[index]), 2)
            predictions.append({
                "rank": rank,
                "crop": crop.title(),
                "confidence": confidence,
                "reasons": [
                    "Prediction generated by the trained crop recommendation model.",
                    "Model uses N, P, K, temperature, humidity, pH, and rainfall."
                ]
            })
        return predictions

    crop = str(model.predict(features)[0])
    return [{
        "rank": 1,
        "crop": crop.title(),
        "confidence": 1.0,
        "reasons": [
            "Prediction generated by the trained crop recommendation model.",
            "Probability scores are not available for this estimator."
        ]
    }]


def model_metadata():
    """Return metadata for the trained crop model."""
    artifact = load_crop_model()
    if artifact is None:
        return None

    return artifact.get("metadata", {})
